; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "D'Clinic System"
#define MyAppVersion "1.0"
#define MyAppPublisher "Demind Concept Design"
#define MyAppURL "https://instagram.com/w.auliaabdillah"
#define MyAppExeName "decode.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{21068367-2CB3-4B3B-888A-F707C79ADD6C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=D:\DC System\DC System
DisableProgramGroupPage=yes
LicenseFile=E:\DATA\3. DESKTOP APP PROJECT\License Agreement.txt
InfoAfterFile=E:\DATA\3. DESKTOP APP PROJECT\After Instalation.txt
OutputDir=C:\Users\Staff-IT\Desktop
OutputBaseFilename=DCS Setup
SetupIconFile=D:\DCS\Stock_Aset_Gudang_Icon2.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\DC System\System\decode.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\DC System\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

